apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-microservices-investing
  labels:
    app: k8s-microservices-investing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-microservices-investing
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: k8s-microservices-investing
    spec:
      containers:
        - name: k8s-microservices-investing-mysql
          image: mariadb
